default_scene: "Chargement"

bindings:

  audio:
    - slider: 0
      name: "Fond sonore"

    - slider: 1
      name: "Bird UM1"

    - slider: 2
      name: "Wireless GO"
      

  scenes:
    - button: 0
      name: "Chargement"

    - button: 1
      name: "Chat"

    - button: 2
      name: "Coding"

    - button: 3
      name: "Atelier Top"

    - button: 4
      name: "Bureau"

    - button: 6
      name: "Pause"

    - button: 7
      name: "Bye"


  sources:

    - button: 16
      name: "Camera Logitech C920"

